/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PostLoginRouteImport } from './routes/post-login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MfaEnrollRouteImport } from './routes/mfa.enroll'
import { Route as MfaChallengeRouteImport } from './routes/mfa.challenge'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthGooglePopupRouteImport } from './routes/auth/google-popup'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicEarlyAccessRouteImport } from './routes/api/public/early-access'
import { Route as AuthenticatedDashboardWatchRouteImport } from './routes/_authenticated/dashboard.watch'
import { Route as AuthenticatedDashboardShieldRouteImport } from './routes/_authenticated/dashboard.shield'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard.reports'
import { Route as AuthenticatedDashboardLegionsRouteImport } from './routes/_authenticated/dashboard.legions'
import { Route as AuthenticatedDashboardGuardianRouteImport } from './routes/_authenticated/dashboard.guardian'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminAdminSigningKeysRouteImport } from './routes/_admin/admin.signing-keys'
import { Route as AdminAdminScoringRouteImport } from './routes/_admin/admin.scoring'
import { Route as AdminAdminRevenueRouteImport } from './routes/_admin/admin.revenue'
import { Route as AdminAdminOperatorRouteImport } from './routes/_admin/admin.operator'
import { Route as AdminAdminMonitoringRouteImport } from './routes/_admin/admin.monitoring'
import { Route as AdminAdminHealthRouteImport } from './routes/_admin/admin.health'
import { Route as AdminAdminGuardianRouteImport } from './routes/_admin/admin.guardian'
import { Route as AdminAdminErrorsRouteImport } from './routes/_admin/admin.errors'
import { Route as AdminAdminCostsRouteImport } from './routes/_admin/admin.costs'
import { Route as AdminAdminConfigRouteImport } from './routes/_admin/admin.config'
import { Route as AdminAdminAuditRouteImport } from './routes/_admin/admin.audit'
import { Route as AdminAdminAgentsRouteImport } from './routes/_admin/admin.agents'
import { Route as AuthenticatedDashboardSettingsIndexRouteImport } from './routes/_authenticated/dashboard.settings.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedDashboardSettingsSubscriptionRouteImport } from './routes/_authenticated/dashboard.settings.subscription'
import { Route as AuthenticatedDashboardSettingsProfileRouteImport } from './routes/_authenticated/dashboard.settings.profile'
import { Route as AuthenticatedDashboardSettingsKeysRouteImport } from './routes/_authenticated/dashboard.settings.keys'
import { Route as AuthenticatedDashboardOperatorSigningKeysRouteImport } from './routes/_authenticated/dashboard.operator.signing-keys'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PostLoginRoute = PostLoginRouteImport.update({
  id: '/post-login',
  path: '/post-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaEnrollRoute = MfaEnrollRouteImport.update({
  id: '/mfa/enroll',
  path: '/mfa/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaChallengeRoute = MfaChallengeRouteImport.update({
  id: '/mfa/challenge',
  path: '/mfa/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGooglePopupRoute = AuthGooglePopupRouteImport.update({
  id: '/auth/google-popup',
  path: '/auth/google-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEarlyAccessRoute = ApiPublicEarlyAccessRouteImport.update({
  id: '/api/public/early-access',
  path: '/api/public/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardWatchRoute =
  AuthenticatedDashboardWatchRouteImport.update({
    id: '/watch',
    path: '/watch',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardShieldRoute =
  AuthenticatedDashboardShieldRouteImport.update({
    id: '/shield',
    path: '/shield',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLegionsRoute =
  AuthenticatedDashboardLegionsRouteImport.update({
    id: '/legions',
    path: '/legions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGuardianRoute =
  AuthenticatedDashboardGuardianRouteImport.update({
    id: '/guardian',
    path: '/guardian',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSigningKeysRoute = AdminAdminSigningKeysRouteImport.update({
  id: '/signing-keys',
  path: '/signing-keys',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminScoringRoute = AdminAdminScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRevenueRoute = AdminAdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOperatorRoute = AdminAdminOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMonitoringRoute = AdminAdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminHealthRoute = AdminAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminGuardianRoute = AdminAdminGuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminErrorsRoute = AdminAdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCostsRoute = AdminAdminCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminConfigRoute = AdminAdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditRoute = AdminAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAgentsRoute = AdminAdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedDashboardSettingsIndexRoute =
  AuthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardSettingsSubscriptionRoute =
  AuthenticatedDashboardSettingsSubscriptionRouteImport.update({
    id: '/settings/subscription',
    path: '/settings/subscription',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsProfileRoute =
  AuthenticatedDashboardSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsKeysRoute =
  AuthenticatedDashboardSettingsKeysRouteImport.update({
    id: '/settings/keys',
    path: '/settings/keys',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOperatorSigningKeysRoute =
  AuthenticatedDashboardOperatorSigningKeysRouteImport.update({
    id: '/operator/signing-keys',
    path: '/operator/signing-keys',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post-login': typeof PostLoginRoute
  '/presentation': typeof PresentationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google-popup': typeof AuthGooglePopupRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/enroll': typeof MfaEnrollRoute
  '/admin/agents': typeof AdminAdminAgentsRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/config': typeof AdminAdminConfigRoute
  '/admin/costs': typeof AdminAdminCostsRoute
  '/admin/errors': typeof AdminAdminErrorsRoute
  '/admin/guardian': typeof AdminAdminGuardianRoute
  '/admin/health': typeof AdminAdminHealthRoute
  '/admin/monitoring': typeof AdminAdminMonitoringRoute
  '/admin/operator': typeof AdminAdminOperatorRoute
  '/admin/revenue': typeof AdminAdminRevenueRoute
  '/admin/scoring': typeof AdminAdminScoringRoute
  '/admin/signing-keys': typeof AdminAdminSigningKeysRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/dashboard/guardian': typeof AuthenticatedDashboardGuardianRoute
  '/dashboard/legions': typeof AuthenticatedDashboardLegionsRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/shield': typeof AuthenticatedDashboardShieldRoute
  '/dashboard/watch': typeof AuthenticatedDashboardWatchRoute
  '/api/public/early-access': typeof ApiPublicEarlyAccessRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/operator/signing-keys': typeof AuthenticatedDashboardOperatorSigningKeysRoute
  '/dashboard/settings/keys': typeof AuthenticatedDashboardSettingsKeysRoute
  '/dashboard/settings/profile': typeof AuthenticatedDashboardSettingsProfileRoute
  '/dashboard/settings/subscription': typeof AuthenticatedDashboardSettingsSubscriptionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post-login': typeof PostLoginRoute
  '/presentation': typeof PresentationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google-popup': typeof AuthGooglePopupRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/enroll': typeof MfaEnrollRoute
  '/admin/agents': typeof AdminAdminAgentsRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/config': typeof AdminAdminConfigRoute
  '/admin/costs': typeof AdminAdminCostsRoute
  '/admin/errors': typeof AdminAdminErrorsRoute
  '/admin/guardian': typeof AdminAdminGuardianRoute
  '/admin/health': typeof AdminAdminHealthRoute
  '/admin/monitoring': typeof AdminAdminMonitoringRoute
  '/admin/operator': typeof AdminAdminOperatorRoute
  '/admin/revenue': typeof AdminAdminRevenueRoute
  '/admin/scoring': typeof AdminAdminScoringRoute
  '/admin/signing-keys': typeof AdminAdminSigningKeysRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/dashboard/guardian': typeof AuthenticatedDashboardGuardianRoute
  '/dashboard/legions': typeof AuthenticatedDashboardLegionsRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/shield': typeof AuthenticatedDashboardShieldRoute
  '/dashboard/watch': typeof AuthenticatedDashboardWatchRoute
  '/api/public/early-access': typeof ApiPublicEarlyAccessRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AdminAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/operator/signing-keys': typeof AuthenticatedDashboardOperatorSigningKeysRoute
  '/dashboard/settings/keys': typeof AuthenticatedDashboardSettingsKeysRoute
  '/dashboard/settings/profile': typeof AuthenticatedDashboardSettingsProfileRoute
  '/dashboard/settings/subscription': typeof AuthenticatedDashboardSettingsSubscriptionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/post-login': typeof PostLoginRoute
  '/presentation': typeof PresentationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google-popup': typeof AuthGooglePopupRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/enroll': typeof MfaEnrollRoute
  '/_admin/admin/agents': typeof AdminAdminAgentsRoute
  '/_admin/admin/audit': typeof AdminAdminAuditRoute
  '/_admin/admin/config': typeof AdminAdminConfigRoute
  '/_admin/admin/costs': typeof AdminAdminCostsRoute
  '/_admin/admin/errors': typeof AdminAdminErrorsRoute
  '/_admin/admin/guardian': typeof AdminAdminGuardianRoute
  '/_admin/admin/health': typeof AdminAdminHealthRoute
  '/_admin/admin/monitoring': typeof AdminAdminMonitoringRoute
  '/_admin/admin/operator': typeof AdminAdminOperatorRoute
  '/_admin/admin/revenue': typeof AdminAdminRevenueRoute
  '/_admin/admin/scoring': typeof AdminAdminScoringRoute
  '/_admin/admin/signing-keys': typeof AdminAdminSigningKeysRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_authenticated/dashboard/guardian': typeof AuthenticatedDashboardGuardianRoute
  '/_authenticated/dashboard/legions': typeof AuthenticatedDashboardLegionsRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/shield': typeof AuthenticatedDashboardShieldRoute
  '/_authenticated/dashboard/watch': typeof AuthenticatedDashboardWatchRoute
  '/api/public/early-access': typeof ApiPublicEarlyAccessRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/operator/signing-keys': typeof AuthenticatedDashboardOperatorSigningKeysRoute
  '/_authenticated/dashboard/settings/keys': typeof AuthenticatedDashboardSettingsKeysRoute
  '/_authenticated/dashboard/settings/profile': typeof AuthenticatedDashboardSettingsProfileRoute
  '/_authenticated/dashboard/settings/subscription': typeof AuthenticatedDashboardSettingsSubscriptionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/post-login'
    | '/presentation'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/google-popup'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/mfa/challenge'
    | '/mfa/enroll'
    | '/admin/agents'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/costs'
    | '/admin/errors'
    | '/admin/guardian'
    | '/admin/health'
    | '/admin/monitoring'
    | '/admin/operator'
    | '/admin/revenue'
    | '/admin/scoring'
    | '/admin/signing-keys'
    | '/admin/users'
    | '/dashboard/guardian'
    | '/dashboard/legions'
    | '/dashboard/reports'
    | '/dashboard/shield'
    | '/dashboard/watch'
    | '/api/public/early-access'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/operator/signing-keys'
    | '/dashboard/settings/keys'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/subscription'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/post-login'
    | '/presentation'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/google-popup'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/mfa/challenge'
    | '/mfa/enroll'
    | '/admin/agents'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/costs'
    | '/admin/errors'
    | '/admin/guardian'
    | '/admin/health'
    | '/admin/monitoring'
    | '/admin/operator'
    | '/admin/revenue'
    | '/admin/scoring'
    | '/admin/signing-keys'
    | '/admin/users'
    | '/dashboard/guardian'
    | '/dashboard/legions'
    | '/dashboard/reports'
    | '/dashboard/shield'
    | '/dashboard/watch'
    | '/api/public/early-access'
    | '/lovable/email/suppression'
    | '/admin'
    | '/dashboard'
    | '/dashboard/operator/signing-keys'
    | '/dashboard/settings/keys'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/subscription'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/post-login'
    | '/presentation'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_admin/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/auth/callback'
    | '/auth/google-popup'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/mfa/challenge'
    | '/mfa/enroll'
    | '/_admin/admin/agents'
    | '/_admin/admin/audit'
    | '/_admin/admin/config'
    | '/_admin/admin/costs'
    | '/_admin/admin/errors'
    | '/_admin/admin/guardian'
    | '/_admin/admin/health'
    | '/_admin/admin/monitoring'
    | '/_admin/admin/operator'
    | '/_admin/admin/revenue'
    | '/_admin/admin/scoring'
    | '/_admin/admin/signing-keys'
    | '/_admin/admin/users'
    | '/_authenticated/dashboard/guardian'
    | '/_authenticated/dashboard/legions'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/shield'
    | '/_authenticated/dashboard/watch'
    | '/api/public/early-access'
    | '/lovable/email/suppression'
    | '/_admin/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/operator/signing-keys'
    | '/_authenticated/dashboard/settings/keys'
    | '/_authenticated/dashboard/settings/profile'
    | '/_authenticated/dashboard/settings/subscription'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PostLoginRoute: typeof PostLoginRoute
  PresentationRoute: typeof PresentationRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthGooglePopupRoute: typeof AuthGooglePopupRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  MfaChallengeRoute: typeof MfaChallengeRoute
  MfaEnrollRoute: typeof MfaEnrollRoute
  ApiPublicEarlyAccessRoute: typeof ApiPublicEarlyAccessRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-login': {
      id: '/post-login'
      path: '/post-login'
      fullPath: '/post-login'
      preLoaderRoute: typeof PostLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/enroll': {
      id: '/mfa/enroll'
      path: '/mfa/enroll'
      fullPath: '/mfa/enroll'
      preLoaderRoute: typeof MfaEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/challenge': {
      id: '/mfa/challenge'
      path: '/mfa/challenge'
      fullPath: '/mfa/challenge'
      preLoaderRoute: typeof MfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google-popup': {
      id: '/auth/google-popup'
      path: '/auth/google-popup'
      fullPath: '/auth/google-popup'
      preLoaderRoute: typeof AuthGooglePopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/early-access': {
      id: '/api/public/early-access'
      path: '/api/public/early-access'
      fullPath: '/api/public/early-access'
      preLoaderRoute: typeof ApiPublicEarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/watch': {
      id: '/_authenticated/dashboard/watch'
      path: '/watch'
      fullPath: '/dashboard/watch'
      preLoaderRoute: typeof AuthenticatedDashboardWatchRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/shield': {
      id: '/_authenticated/dashboard/shield'
      path: '/shield'
      fullPath: '/dashboard/shield'
      preLoaderRoute: typeof AuthenticatedDashboardShieldRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/legions': {
      id: '/_authenticated/dashboard/legions'
      path: '/legions'
      fullPath: '/dashboard/legions'
      preLoaderRoute: typeof AuthenticatedDashboardLegionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/guardian': {
      id: '/_authenticated/dashboard/guardian'
      path: '/guardian'
      fullPath: '/dashboard/guardian'
      preLoaderRoute: typeof AuthenticatedDashboardGuardianRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/signing-keys': {
      id: '/_admin/admin/signing-keys'
      path: '/signing-keys'
      fullPath: '/admin/signing-keys'
      preLoaderRoute: typeof AdminAdminSigningKeysRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/scoring': {
      id: '/_admin/admin/scoring'
      path: '/scoring'
      fullPath: '/admin/scoring'
      preLoaderRoute: typeof AdminAdminScoringRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/revenue': {
      id: '/_admin/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminAdminRevenueRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/operator': {
      id: '/_admin/admin/operator'
      path: '/operator'
      fullPath: '/admin/operator'
      preLoaderRoute: typeof AdminAdminOperatorRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/monitoring': {
      id: '/_admin/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminAdminMonitoringRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/health': {
      id: '/_admin/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminAdminHealthRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/guardian': {
      id: '/_admin/admin/guardian'
      path: '/guardian'
      fullPath: '/admin/guardian'
      preLoaderRoute: typeof AdminAdminGuardianRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/errors': {
      id: '/_admin/admin/errors'
      path: '/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminAdminErrorsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/costs': {
      id: '/_admin/admin/costs'
      path: '/costs'
      fullPath: '/admin/costs'
      preLoaderRoute: typeof AdminAdminCostsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/config': {
      id: '/_admin/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminAdminConfigRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/audit': {
      id: '/_admin/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAdminAuditRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/agents': {
      id: '/_admin/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAdminAgentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/dashboard/settings/': {
      id: '/_authenticated/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/settings/subscription': {
      id: '/_authenticated/dashboard/settings/subscription'
      path: '/settings/subscription'
      fullPath: '/dashboard/settings/subscription'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsSubscriptionRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings/profile': {
      id: '/_authenticated/dashboard/settings/profile'
      path: '/settings/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings/keys': {
      id: '/_authenticated/dashboard/settings/keys'
      path: '/settings/keys'
      fullPath: '/dashboard/settings/keys'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/operator/signing-keys': {
      id: '/_authenticated/dashboard/operator/signing-keys'
      path: '/operator/signing-keys'
      fullPath: '/dashboard/operator/signing-keys'
      preLoaderRoute: typeof AuthenticatedDashboardOperatorSigningKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAgentsRoute: typeof AdminAdminAgentsRoute
  AdminAdminAuditRoute: typeof AdminAdminAuditRoute
  AdminAdminConfigRoute: typeof AdminAdminConfigRoute
  AdminAdminCostsRoute: typeof AdminAdminCostsRoute
  AdminAdminErrorsRoute: typeof AdminAdminErrorsRoute
  AdminAdminGuardianRoute: typeof AdminAdminGuardianRoute
  AdminAdminHealthRoute: typeof AdminAdminHealthRoute
  AdminAdminMonitoringRoute: typeof AdminAdminMonitoringRoute
  AdminAdminOperatorRoute: typeof AdminAdminOperatorRoute
  AdminAdminRevenueRoute: typeof AdminAdminRevenueRoute
  AdminAdminScoringRoute: typeof AdminAdminScoringRoute
  AdminAdminSigningKeysRoute: typeof AdminAdminSigningKeysRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAgentsRoute: AdminAdminAgentsRoute,
  AdminAdminAuditRoute: AdminAdminAuditRoute,
  AdminAdminConfigRoute: AdminAdminConfigRoute,
  AdminAdminCostsRoute: AdminAdminCostsRoute,
  AdminAdminErrorsRoute: AdminAdminErrorsRoute,
  AdminAdminGuardianRoute: AdminAdminGuardianRoute,
  AdminAdminHealthRoute: AdminAdminHealthRoute,
  AdminAdminMonitoringRoute: AdminAdminMonitoringRoute,
  AdminAdminOperatorRoute: AdminAdminOperatorRoute,
  AdminAdminRevenueRoute: AdminAdminRevenueRoute,
  AdminAdminScoringRoute: AdminAdminScoringRoute,
  AdminAdminSigningKeysRoute: AdminAdminSigningKeysRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardGuardianRoute: typeof AuthenticatedDashboardGuardianRoute
  AuthenticatedDashboardLegionsRoute: typeof AuthenticatedDashboardLegionsRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardShieldRoute: typeof AuthenticatedDashboardShieldRoute
  AuthenticatedDashboardWatchRoute: typeof AuthenticatedDashboardWatchRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardOperatorSigningKeysRoute: typeof AuthenticatedDashboardOperatorSigningKeysRoute
  AuthenticatedDashboardSettingsKeysRoute: typeof AuthenticatedDashboardSettingsKeysRoute
  AuthenticatedDashboardSettingsProfileRoute: typeof AuthenticatedDashboardSettingsProfileRoute
  AuthenticatedDashboardSettingsSubscriptionRoute: typeof AuthenticatedDashboardSettingsSubscriptionRoute
  AuthenticatedDashboardSettingsIndexRoute: typeof AuthenticatedDashboardSettingsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardGuardianRoute: AuthenticatedDashboardGuardianRoute,
    AuthenticatedDashboardLegionsRoute: AuthenticatedDashboardLegionsRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardShieldRoute: AuthenticatedDashboardShieldRoute,
    AuthenticatedDashboardWatchRoute: AuthenticatedDashboardWatchRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardOperatorSigningKeysRoute:
      AuthenticatedDashboardOperatorSigningKeysRoute,
    AuthenticatedDashboardSettingsKeysRoute:
      AuthenticatedDashboardSettingsKeysRoute,
    AuthenticatedDashboardSettingsProfileRoute:
      AuthenticatedDashboardSettingsProfileRoute,
    AuthenticatedDashboardSettingsSubscriptionRoute:
      AuthenticatedDashboardSettingsSubscriptionRoute,
    AuthenticatedDashboardSettingsIndexRoute:
      AuthenticatedDashboardSettingsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PostLoginRoute: PostLoginRoute,
  PresentationRoute: PresentationRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthGooglePopupRoute: AuthGooglePopupRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  MfaChallengeRoute: MfaChallengeRoute,
  MfaEnrollRoute: MfaEnrollRoute,
  ApiPublicEarlyAccessRoute: ApiPublicEarlyAccessRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
