/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostLoginRouteImport } from './routes/post-login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthGooglePopupRouteImport } from './routes/auth/google-popup'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedSuggestionsRouteImport } from './routes/_authenticated/suggestions'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLoopRouteImport } from './routes/_authenticated/loop'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedSettingsKeysRouteImport } from './routes/_authenticated/settings.keys'
import { Route as AuthenticatedDashboardWatchRouteImport } from './routes/_authenticated/dashboard.watch'
import { Route as AuthenticatedDashboardShieldRouteImport } from './routes/_authenticated/dashboard.shield'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard.reports'
import { Route as AuthenticatedDashboardLegionsRouteImport } from './routes/_authenticated/dashboard.legions'
import { Route as AuthenticatedDashboardGuardianRouteImport } from './routes/_authenticated/dashboard.guardian'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostLoginRoute = PostLoginRouteImport.update({
  id: '/post-login',
  path: '/post-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGooglePopupRoute = AuthGooglePopupRouteImport.update({
  id: '/auth/google-popup',
  path: '/auth/google-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuggestionsRoute =
  AuthenticatedSuggestionsRouteImport.update({
    id: '/suggestions',
    path: '/suggestions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoopRoute = AuthenticatedLoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedSettingsKeysRoute =
  AuthenticatedSettingsKeysRouteImport.update({
    id: '/settings/keys',
    path: '/settings/keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardWatchRoute =
  AuthenticatedDashboardWatchRouteImport.update({
    id: '/watch',
    path: '/watch',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardShieldRoute =
  AuthenticatedDashboardShieldRouteImport.update({
    id: '/shield',
    path: '/shield',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLegionsRoute =
  AuthenticatedDashboardLegionsRouteImport.update({
    id: '/legions',
    path: '/legions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGuardianRoute =
  AuthenticatedDashboardGuardianRouteImport.update({
    id: '/guardian',
    path: '/guardian',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post-login': typeof PostLoginRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/loop': typeof AuthenticatedLoopRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/suggestions': typeof AuthenticatedSuggestionsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google-popup': typeof AuthGooglePopupRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/guardian': typeof AuthenticatedDashboardGuardianRoute
  '/dashboard/legions': typeof AuthenticatedDashboardLegionsRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/shield': typeof AuthenticatedDashboardShieldRoute
  '/dashboard/watch': typeof AuthenticatedDashboardWatchRoute
  '/settings/keys': typeof AuthenticatedSettingsKeysRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post-login': typeof PostLoginRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/loop': typeof AuthenticatedLoopRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/suggestions': typeof AuthenticatedSuggestionsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google-popup': typeof AuthGooglePopupRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/guardian': typeof AuthenticatedDashboardGuardianRoute
  '/dashboard/legions': typeof AuthenticatedDashboardLegionsRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/shield': typeof AuthenticatedDashboardShieldRoute
  '/dashboard/watch': typeof AuthenticatedDashboardWatchRoute
  '/settings/keys': typeof AuthenticatedSettingsKeysRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/post-login': typeof PostLoginRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/loop': typeof AuthenticatedLoopRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/policies': typeof AuthenticatedPoliciesRoute
  '/_authenticated/suggestions': typeof AuthenticatedSuggestionsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google-popup': typeof AuthGooglePopupRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/dashboard/guardian': typeof AuthenticatedDashboardGuardianRoute
  '/_authenticated/dashboard/legions': typeof AuthenticatedDashboardLegionsRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/shield': typeof AuthenticatedDashboardShieldRoute
  '/_authenticated/dashboard/watch': typeof AuthenticatedDashboardWatchRoute
  '/_authenticated/settings/keys': typeof AuthenticatedSettingsKeysRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/post-login'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/dashboard'
    | '/loop'
    | '/onboarding'
    | '/policies'
    | '/suggestions'
    | '/today'
    | '/auth/callback'
    | '/auth/google-popup'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/guardian'
    | '/dashboard/legions'
    | '/dashboard/reports'
    | '/dashboard/shield'
    | '/dashboard/watch'
    | '/settings/keys'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/post-login'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/loop'
    | '/onboarding'
    | '/policies'
    | '/suggestions'
    | '/today'
    | '/auth/callback'
    | '/auth/google-popup'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/guardian'
    | '/dashboard/legions'
    | '/dashboard/reports'
    | '/dashboard/shield'
    | '/dashboard/watch'
    | '/settings/keys'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/post-login'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/loop'
    | '/_authenticated/onboarding'
    | '/_authenticated/policies'
    | '/_authenticated/suggestions'
    | '/_authenticated/today'
    | '/auth/callback'
    | '/auth/google-popup'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/_authenticated/dashboard/guardian'
    | '/_authenticated/dashboard/legions'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/shield'
    | '/_authenticated/dashboard/watch'
    | '/_authenticated/settings/keys'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PostLoginRoute: typeof PostLoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthGooglePopupRoute: typeof AuthGooglePopupRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-login': {
      id: '/post-login'
      path: '/post-login'
      fullPath: '/post-login'
      preLoaderRoute: typeof PostLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google-popup': {
      id: '/auth/google-popup'
      path: '/auth/google-popup'
      fullPath: '/auth/google-popup'
      preLoaderRoute: typeof AuthGooglePopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suggestions': {
      id: '/_authenticated/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof AuthenticatedSuggestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loop': {
      id: '/_authenticated/loop'
      path: '/loop'
      fullPath: '/loop'
      preLoaderRoute: typeof AuthenticatedLoopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/settings/keys': {
      id: '/_authenticated/settings/keys'
      path: '/settings/keys'
      fullPath: '/settings/keys'
      preLoaderRoute: typeof AuthenticatedSettingsKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/watch': {
      id: '/_authenticated/dashboard/watch'
      path: '/watch'
      fullPath: '/dashboard/watch'
      preLoaderRoute: typeof AuthenticatedDashboardWatchRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/shield': {
      id: '/_authenticated/dashboard/shield'
      path: '/shield'
      fullPath: '/dashboard/shield'
      preLoaderRoute: typeof AuthenticatedDashboardShieldRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/legions': {
      id: '/_authenticated/dashboard/legions'
      path: '/legions'
      fullPath: '/dashboard/legions'
      preLoaderRoute: typeof AuthenticatedDashboardLegionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/guardian': {
      id: '/_authenticated/dashboard/guardian'
      path: '/guardian'
      fullPath: '/dashboard/guardian'
      preLoaderRoute: typeof AuthenticatedDashboardGuardianRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardGuardianRoute: typeof AuthenticatedDashboardGuardianRoute
  AuthenticatedDashboardLegionsRoute: typeof AuthenticatedDashboardLegionsRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardShieldRoute: typeof AuthenticatedDashboardShieldRoute
  AuthenticatedDashboardWatchRoute: typeof AuthenticatedDashboardWatchRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardGuardianRoute: AuthenticatedDashboardGuardianRoute,
    AuthenticatedDashboardLegionsRoute: AuthenticatedDashboardLegionsRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardShieldRoute: AuthenticatedDashboardShieldRoute,
    AuthenticatedDashboardWatchRoute: AuthenticatedDashboardWatchRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedLoopRoute: typeof AuthenticatedLoopRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRoute
  AuthenticatedSuggestionsRoute: typeof AuthenticatedSuggestionsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedSettingsKeysRoute: typeof AuthenticatedSettingsKeysRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedLoopRoute: AuthenticatedLoopRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRoute,
  AuthenticatedSuggestionsRoute: AuthenticatedSuggestionsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedSettingsKeysRoute: AuthenticatedSettingsKeysRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PostLoginRoute: PostLoginRoute,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthGooglePopupRoute: AuthGooglePopupRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
